### ISSUE TITLE
git无法连接远程库的问题?

### ISSUE THREAD

**Issue by greenHard** [judasn/IntelliJ-IDEA-Tutorial#104]
版本: 2018.2.2  2018.2.3
    这两个版本我都试了,本地2017年的版本能正常使用
   2018的两个版本git都无法连接到远程仓库。

**Comment by judasn** [comment]
在设置：File | Settings | Version Control | GitHub
中添加账号试试

**Comment by greenHard** [comment]
@judasn 不是GitHub,是使用ssh连接公司内部git仓库gitlib,无法获取到远程库。2017.3.1版本正常。2018.2版才有的问题?
