### ISSUE TITLE
更新Mojave后出现问题

### ISSUE THREAD

**Issue by zwdgit** [judasn/IntelliJ-IDEA-Tutorial#105]
今天更新了Mojave正式版系统，之后打开IntelliJ 系列软件都需要等待很长时间才能进到加载界面，请问这个问题有办法解决没？

**Comment by judasn** [comment]
我暂时还没有更新到最新系统...
如果有类似问题就只能到官网社区找下是否有类似的，一般这个只能靠官网出方案。
