### ISSUE TITLE
vim 的相关操作没有提到, 后续会考虑这个吗?

### ISSUE THREAD

**Issue by MasterShu** [judasn/IntelliJ-IDEA-Tutorial#119]
vim 的相关操作没有提到, 后续会考虑这个吗?

**Comment by judasn** [comment]
VIM 的操作本质就是 VIM，如果没有 VIM 经验也可以看这里：
https://github.com/judasn/Linux-Tutorial/blob/master/markdown-file/Vim-Install-And-Settings.md

IntelliJ IDEA 中对 VIM 有点点小区别，可以直接看这里：
https://www.jetbrains.com/help/idea/using-product-as-the-vim-editor.html

**Comment by gamenessman** [comment]
赞
