### ISSUE TITLE
建议使用 Github Page

### ISSUE THREAD

**Issue by sky5454** [judasn/IntelliJ-IDEA-Tutorial#123]
启用 Github Page ，然后再找个主题生成，就可以实时阅读了，不需要多次操作生成。

**Comment by judasn** [comment]
不推荐。因为目前的 Github Page 在做文档上不友好，做博客这类倒是还可以。

从我目前个人体验上，gitbook 更适合阅读。
gitbook 版本我已经发布了：https://youmeek.gitbooks.io/intellij-idea-tutorial/content/

我个人一直很喜欢用 IntelliJ IDEA 写文章，git 做版本管理。
也是我认为该方案是目前最优的写作方案，所以我希望能引导到更多的人。
