### ISSUE TITLE
关于2019.2的更新中文字体显示的问题

### ISSUE THREAD

**Issue by hearsay316** [judasn/IntelliJ-IDEA-Tutorial#124]
如图所示, 中文显示的字体全换了,如何更改

**Comment by hearsay316** [comment]
![01](https://user-images.githubusercontent.com/10139810/62018700-5d782b00-b1ee-11e9-803d-e2eb213226d0.png)

**Comment by hearsay316** [comment]
![微信截图_20190729104523](https://user-images.githubusercontent.com/10139810/62018718-71239180-b1ee-11e9-8d47-147bb0bfa97e.png)

**Comment by judasn** [comment]
- 现在没在 Win 下开发了，不清楚 Win 下的情况。
- Mac 我这边测试是没问题的
- 理论上字体修改还是那几个地方你可以参考这篇文章 [点击我](https://github.com/judasn/IntelliJ-IDEA-Tutorial/blob/master/theme-settings.md)
