### ISSUE TITLE
idea2019.2maven仓库配置页空白

### ISSUE THREAD

**Issue by hhui197** [judasn/IntelliJ-IDEA-Tutorial#125]
![image](https://user-images.githubusercontent.com/48912127/63342586-6f2c9880-c37e-11e9-81f4-0cacfc8b1e2e.png)
idea配置是从以前版本上导出的没变，但是Repositories就是空白的，pom里面没有了提示很难受

**Comment by judasn** [comment]
在我的 2019 版本里，我也没看到。
但是我一直认为这个不准或是网络不通畅。我个人更愿意去 maven 官网站去查，
这样会自我感觉比较靠谱...Orz
