### ISSUE TITLE
关于jsprun这个示例代码的一处编译报错

### ISSUE THREAD

**Issue by cullenx** [judasn/IntelliJ-IDEA-Tutorial#13]
\JspRun\WebRoot\templates\default\stats_main.jsp  
第270行  
`<c:forEach items="${valueObject.monthFlux}"var="pageInfo">  `
应改为  
`<c:forEach items="${valueObject.monthFlux}" var="pageInfo">  `
jsp规范  属性前必须有空格  ``

**Comment by CrazyBeginner** [comment]
good
