### ISSUE TITLE
教程中图片失效

### ISSUE THREAD

**Issue by ZeroOvO** [judasn/IntelliJ-IDEA-Tutorial#131]
您好，您的教程中图片失效，是否可以修复

**Comment by linsuiyuan** [comment]
> 您好，您的教程中图片失效，是否可以修复

图片没有失效，你加载不出来，大概是被墙了

**Comment by huangj0612** [comment]
你好，也碰到同样的问题，通过修改host文件，解决了，可以上网查一下

@xumoomux

**Comment by marklong5** [comment]
同问，图片失效加载不出来。

**Comment by cdk8s-zelda** [comment]
> 同问，图片失效加载不出来。

图片没失效，被强而且。
推荐使用 https://cdk8s.gitbook.io/github/ 查看
