### ISSUE TITLE
来求输入法的

### ISSUE THREAD

**Issue by helloyan** [judasn/IntelliJ-IDEA-Tutorial#14]
![image](https://cloud.githubusercontent.com/assets/1699033/15567372/9227d300-2358-11e6-836e-215a569f6b4f.png)
什么输入法

**Comment by judasn** [comment]
1.搜狗
2.特殊在皮肤，这个皮肤下载：https://yunpan.cn/cS2XXmWZezDEk （提取码：69e4）
