### ISSUE TITLE
不需要HTML、MD文档、电子书都发一份吧

### ISSUE THREAD

**Issue by adushui** [judasn/IntelliJ-IDEA-Tutorial#16]
这样有错误修改起来要改3个地方，算上“/”下的极客学院，4份。

电子书有70+M，我觉得可以删了，不是实时更新，不如直接使用网盘加个说明好了。
`touch CHM版请到网盘下载`

刚才clone到本地，碰上宽带炸了，这个repo有250M，时间感人。

**Comment by adushui** [comment]
建议不必要同时维护 / 、/CHM电子版本/源HTML文件、/CHM电子版本/源MD文件 三处文档（内容一样，工作量太大）

**Comment by judasn** [comment]
我也有这个感觉，但是可能因为已经发上去了，所以就没在意了，但是确实不适合，我自己也不喜欢，所以我还是删掉吧。

**Comment by adushui** [comment]
最近在学习git，如果需要清除已经提交到本地仓库的CHM，使用以下命令即可。
当然，不一定需要这样做。
just mark
`git filter-branch --force --index-filter 'git rm --cached --ignore-unmatch CHM电子版本/IntelliJ IDEA 简体中文专题教程（电子版-2015）.CHM' --prune-empty --tag-name-filter cat -- --all`

**Comment by judasn** [comment]
电子书的下载地址在readme上就有提供下载地址的。
但是电子书的版本后面没更新了，所以不建议你下载。
最新版的电子书没打算做了，费劲。有需要的人自己做吧。不然我们一般都是连着网络，所以基本不需要离线的时候。如果有这种时候，用手机也可以及时查一下，所以懒得做电子书了，没啥鸟用。
