### ISSUE TITLE
极客学院的wiki图片不显示了

### ISSUE THREAD

**Issue by liangfhNoDev** [judasn/IntelliJ-IDEA-Tutorial#26]
极客学院的wiki图片不显示了，全是404，下面很多用户都评论图片挂了，麻烦作者有空的话修复一下哈，我估计您可能太忙没时间看wiki就来github反映了。

**Comment by judasn** [comment]
感谢，已经反馈给极客学院，他们那边的系统有点问题，webhook不时出现这样
