### ISSUE TITLE
极客学院wiki中图片不显示了

### ISSUE THREAD

**Issue by AsanZhang** [judasn/IntelliJ-IDEA-Tutorial#27]

**Comment by judasn** [comment]
嗯，我反馈了给极客学院，他们在处理，可能处理速度有点慢或是咋啦，建议你们直接先到Github上来看吧。

**Comment by newlethe** [comment]
效率还是慢很多，截止目前，图片问题依旧没有得到处理，还是只能在这边查看较为方便。

**Comment by SmallerPig** [comment]
到目前为止，还没解决~
本来以为在极客学院看会快一点，结果……

**Comment by judasn** [comment]
极客学院那边现在不怎么维护wiki了，建议大家还是自己下载下来本地查看吧，我也没办法。

**Comment by 9527q** [comment]
但是readme上还写着“建议去极客学院看”的建议呢
