### ISSUE TITLE
一个清爽的 HTML 阅读版

### ISSUE THREAD

**Issue by district10** [judasn/IntelliJ-IDEA-Tutorial#28]
放到网盘上了：

- 在线查看：<http://whudoc.qiniudn.com/2016/IntelliJ-IDEA-Tutorial>
- 下载打包：<http://whudoc.qiniudn.com/2016/publish-IntelliJ-IDEA-Tutorial-newMaster.zip> （90.4 MB）

转化脚本：[district10/md2html: 把文件夹下的 Markdown 文件，转化成 GitHub 风格的 HTML。](https://github.com/district10/md2html)。

上面的 repo 还有一个 Java 版的。今天死磕了很久（第一次用 Java），似乎也可以用了，只需要安装 pandoc 就能使用。;)

Java 版的跨平台，而且只需要安装 pandoc 即可使用。还可以监控修改并自动重新生成 html。

**Comment by rayzfit** [comment]
打包下载解压报错 @district10

**Comment by district10** [comment]
@rayzfit 确实损坏了。更新了下载链接。

**Comment by judasn** [comment]
非常非常非常地感谢！！！
我放在主页，真心辛苦了！
看了你博客，认真的人都是可爱的，加油！

**Comment by district10** [comment]
@judasn 好激动~感谢~

**Comment by Robot-L** [comment]
给楼主点赞，顺便问一下，网页版和作者github上的版本同步吗，是不是最新的？

**Comment by district10** [comment]
@Robot-L  不是的, 你可以用那个 jar 自己运行一下.
