### ISSUE TITLE
请教一个设置的问题

### ISSUE THREAD

**Issue by maskmatch** [judasn/IntelliJ-IDEA-Tutorial#30]
user.getString(**name:**"zhang");
如上"name:"部分不是代码,是IDEA的提示,如何关闭这个提示?有时候很占地方.

**Comment by MrLhp** [comment]
@maskmatch 关闭直接在你示例的name处右键，可以选择disable parameter name hints，如何开启可以在keymap中搜索toggle parameter name hints 配置一个键位，使用快捷键就可以开启了。
