### ISSUE TITLE
文中提到的这个文件在哪

### ISSUE THREAD

**Issue by Aheadboy** [judasn/IntelliJ-IDEA-Tutorial#31]
请问，文中提到的这个文件在哪 《IntelliJ IDEA 相关核心文件和目录介绍》

**Comment by lelewolf** [comment]
http://www.phperz.com/article/15/0923/159061.html

**Comment by judasn** [comment]
https://github.com/judasn/IntelliJ-IDEA-Tutorial/blob/newMaster/installation-directory-introduce.md
