### ISSUE TITLE
eclipse 迁移 到intellij maven设置问题。

### ISSUE THREAD

**Issue by Aheadboy** [judasn/IntelliJ-IDEA-Tutorial#32]
有一个modules依赖了maven，intellij 已经按照eclipse 配置了maven，但是这个modules还是识别不到maven下的一个依赖。
![image](https://cloud.githubusercontent.com/assets/8358046/21466309/1d8e9916-ca01-11e6-872f-ac7d3b212a75.png)

**Comment by judasn** [comment]
intellij 已经按照eclipse 配置了maven，这句话有问题。IntelliJ IDEA 的maven配置跟Eclipse没啥关系，你需要单独去看本教程有关maven项目的文章。

**Comment by Aheadboy** [comment]
这里的按照，我的意思是，maven的路径是按照原来在eclipse里面的路径。原来eclipse路径是可用的。我想告诉回答者，路径已经填写正确。
