### ISSUE TITLE
下载打包地址失效

### ISSUE THREAD

**Issue by binarywang** [judasn/IntelliJ-IDEA-Tutorial#45]
下载打包：http://whudoc.qiniudn.com/2016/publish-IntelliJ-IDEA-Tutorial-newMaster.zip （90.4 MB）

这地址点击报错：

> {
> error: "Document not found"
> }

**Comment by judasn** [comment]
ok，因为是其他人帮忙的，可能他不在维护了，所以我去掉就好了。虽然github访问慢点，但还是可以用的。
