### ISSUE TITLE
Intellij-IDEA Tomcat Plugins

### ISSUE THREAD

**Issue by Jandaes** [judasn/IntelliJ-IDEA-Tutorial#46]
请问下、Intellij-IDEA Tomcat Plugins 热部署的有没有教程，网上的试过很多个、都没有用啊

**Comment by judasn** [comment]
真正的热部署只有：JRebel。https://github.com/judasn/IntelliJ-IDEA-Tutorial/blob/newMaster/jrebel-setup.md
