### ISSUE TITLE
40.IntelliJ IDEA 插件开发视频教程地址失效

### ISSUE THREAD

**Issue by huoguangjin** [judasn/IntelliJ-IDEA-Tutorial#52]
[视频教程](https://github.com/judasn/IntelliJ-IDEA-Tutorial/blob/newMaster/plugins-develop.md) 里的下载地址失效
_(:з」∠)_ 请问视频还在吗 传智播客上也找不到了

**Comment by judasn** [comment]
我这边试了一下，两个视频地址都是存在的呀

**Comment by huoguangjin** [comment]
嗯 链接是正常的
可能是我当时在内网访问不了 晕 不好意思
