### ISSUE TITLE
为什么我取消订阅Issues还会收到邮件提醒？

### ISSUE THREAD

**Issue by FtdConcept** [judasn/IntelliJ-IDEA-Tutorial#53]

**Comment by nanquanyuhao** [comment]
因为watch？

**Comment by FtdConcept** [comment]
没有 我只是start了，没有watch

**Comment by Jandaes** [comment]
![image](https://user-images.githubusercontent.com/9146622/27533812-8623b9d0-5a97-11e7-95d7-be0318a25316.png)    
这里可以取消吧

**Comment by FtdConcept** [comment]
@Jandaes 是的这样可以，但是如果又出现一个新issue,就又会邮件提醒我  - -

**Comment by Jandaes** [comment]
取消关注吧 @FtdConcept

**Comment by FtdConcept** [comment]
@Jandaes 好的，我先试下，看是否可以，谢谢
