### ISSUE TITLE
笔误

### ISSUE THREAD

**Issue by 791934554** [judasn/IntelliJ-IDEA-Tutorial#58]
您好！
从 Windows 过度到 Mac 必备快捷键对照表（keymap-win-mac.md ）发现一个小笔误。

位置：Ctrl + Shfit 快捷键的第二行。

Win 快捷键 | Mac 快捷键 | 介绍
-- | -- | --
Ctrl + Shift + F | Command + Shift + F | 根据输入内容查找整个项目 或 指定目录内文件
Ctrl + Shift + R | Command + Shift + **F(此处应为R)** | 根据输入内容替换对应内容，范围为整个项目 或 指定目录内文件

非常感谢您的分享。

**Comment by judasn** [comment]
很棒，很感谢~~
