### ISSUE TITLE
使用版本控制控制工具的问题

### ISSUE THREAD

**Issue by cuisama** [judasn/IntelliJ-IDEA-Tutorial#63]
能否在获取最新版本的代码之前比对服务器代码和本地代码有哪些不同（哪些文件做了修改，就像eclipse那样），不行的话，在代码更新后，展示前后两个版本的代码的异同也行。
使用的是vss同步visual sourcesafe integration 插件
svn的Repository的tab,能达成这种效果吗

**Comment by judasn** [comment]
1. Git 必须是更新下来才能看到异同。
2. SVN 在 Tab：Version Control 下有一个 Refresh 按钮，点击后可以看服务器最新版本记录，可以看到异同。

**Comment by cuisama** [comment]
@judasn  vss应该不算git吧
eclipse可以在工程上右键 比对整个工程有哪些文件出现在了变更
我觉得intellij应该也支持在文件夹上右键进行compare with..   是真的没有吗，或者官方能为插件追加该功能吗

**Comment by judasn** [comment]
1.微软的 VSS 我没用过，但是 SVN 可以，操作按钮在 Version Control 这个 Tab 上。
2.如果你作为 IntelliJ IDEA 的开发者，同样的功能你不会设计在不同地方的。所以你可以研究下这个 Tab 下的操作按钮，有就有了，没有就没有了。

**Comment by cuisama** [comment]
@judasn 好的 谢谢
