### ISSUE TITLE
5Kfork , 0 issue?

### ISSUE THREAD

**Issue by WestCoastBaby** [judasn/IntelliJ-IDEA-Tutorial#64]
我想知道idea中的jars 和libraries有什么区别？

**Comment by judasn** [comment]
1.jars 这个表达不够准确，称呼完整 jars and directories 其他人好理解。顾名思义就是可以引入 jar 或是目录。它的特点是，只针对单个 module。如果你有 100 个module（外国的开源项目有百来个 module 是有的），你要自己选择 100 次目录位置。
2.libraries 的好处在于添加后，其他 module 可以直接选择 libraries 列表的，无需再去定位项目目录位置了。
3.以上是我的理解，至于 IntelliJ IDEA 开发者的初衷那就不清楚了，得看他们的需求文档了~
