### ISSUE TITLE
demo运行不成功

### ISSUE THREAD

**Issue by liuzhi1986** [judasn/IntelliJ-IDEA-Tutorial#88]
您好，build你的demo时，首先数据库链接超时，其次所有的log.trace中的log都报错显示can't resolve symbol 'log'，具备问题详见下图，个人刚刚开始接触java相关的东西，还请不吝赐教。
![image](https://user-images.githubusercontent.com/17636067/39201210-e45ed5ee-4820-11e8-8394-a07945fdb502.png)

![image](https://user-images.githubusercontent.com/17636067/39201364-68c1019a-4821-11e8-8166-6a87d1291bae.png)

**Comment by judasn** [comment]
1.我看到你有拿到数据，连接数据库没问题
2.log 报错是因为有 lombok 的 IntelliJ IDEA 插件。你需要先用它，具体可以查看文章：[点击我o(∩_∩)o ](https://github.com/judasn/IntelliJ-IDEA-Tutorial/blob/master/plugins-settings.md)
3.lombok 在 Java 业界用的比较多，具体的知识可以 google 下。
