### ISSUE TITLE
版本控制Git分支切换的疑问

### ISSUE THREAD

**Issue by loliskye** [judasn/IntelliJ-IDEA-Tutorial#95]
切换分支：
`checkout` 和 `checkout as` 以及 `checkout with rebase`
这三者有什么区别么？

**Comment by laureler** [comment]
checkout 很简单，就是最基础的checkout，检出你的一个分支。
checkout as 也很简单（学好英语啊，大兄弟，初中就有as的用法了），就是以***为别名，检出一个项目。as的用法本身就是Use a knife as a weapon(用一把刀做为武器）。checkout aaa as bbb.检出aaa分支作为bbb来使用，这个再简单不过。
checkout with rebase。 就是checkout的时候，同时使用rebase。rebase的用法，参考这里：http://gitbook.liuhui998.com/4_2.html

**Comment by williamBoss** [comment]
谢谢

**Comment by loliskye** [comment]
thx :)
