### ISSUE TITLE
tomcat部署项目疑惑

### ISSUE THREAD

**Issue by laureler** [judasn/IntelliJ-IDEA-Tutorial#96]
在tomcat部署的教程中，题主曾经写过，可以将artifact设置为 exploed，同时也可以删掉默认的make过程，在此有几点疑问想要咨询一下。
![image](https://user-images.githubusercontent.com/26224399/43692296-39880944-9959-11e8-9455-5cc1193b6ccd.png)

1. 在我的intellij上，此命令是build，而不是make.
2. build命令/或者你所说的make命令，作用是否是一样的，若一样，那么它的作用是什么？若不一样，能否具体说明？

**Comment by judasn** [comment]
如 loliskye 童鞋说的，在 2018 后面的版本，名称已经改了。
但是道理是一样，就是一个编译的过程。

**Comment by laureler** [comment]
thanks 多谢指导
